# Bot token, retrieved from https://discordapp.com/developers/applications/me
token: XXXXXXXXXXXXXXXXXXXXXXXX.XXXXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXX
# GuildID, see ... for information on how to retrieve this!
guild: 0

# Game presence on Discord, see ... for more information
presence:
  enabled: false
  type-status: ONLINE
  type-activity: PLAYING
  text: 'Linking servers...'

# Message format type in Discord, see ... for more information
message-format:
  type: webhook
  render: 'https://visage.surgeplay.com/head/128/#uuid'
  discord: '#USER: #MESSAGE'

console-channel: 0
shutdown-channel: 0

locale: auto

account-linking:
  enabled: true
  online-role:
    enabled: false
    role: 0

linked-worlds:
  world: 0
  world_nether: 0
  world_the_end: 0

# Please don't touch these options
first-startup: true
