# Please read the documentation at ...
token: xxxxxxxxxxxxxxxxxxxxxxxx.xxxxxx.xxxxxxxxxxxxxxxxxxxxxxxxxxx

invite: 0

channels:
  world: 0
#  global: 0
#  status: 0
#  console: 0

#disabled-dependencies:
#  - MinecraftDiscord

presence:
  enabled: true
  activity: playing
  status: online
  text: Minecraft

options:
  disable-automated-users: true
  require-linking: false
#  process-console: true
  linking-enabled: true
  truncation-size: 256
  message-render: https://visage.surgeplay.com/head/128/<uuid>
  message-type: embed
  language: en
  prefix: /
#  blocked-users:
#    - 0

connection-role:
  enabled: false
  unique: 0

translated-expressions:
  '&[0-9A-Fa-fK-Ok-oRr]': ""
  '\s{4,}': " "

#command-execution:
#  "+ip": "play.example.com"
#  "+shop": "https://shop.example.com"

role-synchronization:
  synchronization-time: 300
#  disallow-unlinking: true
  synchronizable-roles:
    - 0