name: ${project.name}
version: ${project.version}
main: ${project.groupId}.${project.artifactId}
authors: [Jordieh]
description: ${project.description}
website: ${project.url}

softdepend: [PremiumVanish, SuperVanish, VanishNoPacket]

commands:
  link:
    permission: minecraftdiscord.connect
    usage: /<command>
  unlink:
    usage: /<command>
  discord:
    usage: /<command>

permissions:
  minecraftdiscord.connect:
    description: Use the /link command
